contract_abi: '[ /* ABI JSON here */ ]'
contract_address: '0xe213D8b68cA3d01e51a6dBA669De59AC9A8359eE'
default_account: 0xYourAccount
enforce_eager: false
eth_node: http://localhost:8545
gpu_memory_utilization: 0.8
head_min_ram: 8589934592
head_min_vram: 8589934592
ipfs_host: 127.0.0.1
ipfs_port: 5001
max_cpu: 90
max_model_len: 2048
max_tokens: 512
min_free_ram: 2147483648
min_free_vram: 4294967296
model_registry_address: '0x3Dc2cd8F2E345951508427872d8ac9f635fBe0EC'
node_profile_registry_address: '0x880EC53Af800b5Cd051531672EF4fc4De233bD5d'
private_key: 0xYourPrivateKey
ray_port: 6379
stop_tokens: null
temperature: 0.7
top_p: 0.9
trust_remote_code: true
vllm_port: 8000
