contract_abi: '[ /* ABI JSON here */ ]'
contract_address: '0x2F415f51FD16900fc1F92943B1F9A07F1b7EEa14'
default_account: 0xYourAccount
enforce_eager: false
eth_node: http://localhost:8545
gpu_memory_utilization: 0.8
head_min_ram: 8589934592
head_min_vram: 8589934592
ipfs_host: 127.0.0.1
ipfs_port: 5001
max_cpu: 90
max_model_len: 2048
max_tokens: 512
min_free_ram: 2147483648
min_free_vram: 4294967296
model_registry_address: '0x2139B5Baf855EEE55Cdb5F19dF50583585581EaD'
node_profile_registry_address: '0xD91Fb8750Ea1decEf4cEE9D8314f4a60DE039457'
private_key: 0xYourPrivateKey
ray_port: 6379
stop_tokens: null
temperature: 0.7
top_p: 0.9
trust_remote_code: true
vllm_port: 8000
