api:
  cors_enabled: true
  host: 0.0.0.0
  port: 8001
  rate_limit: 100
contract_address: '0x537e697c7AB75A26f9ECF0Ce810e3154dFcaaf44'
default_account: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
development:
  auto_reload: true
  debug: true
  mock_services: false
  test_mode: false
eth_node: https://bootstrap-node.onrender.com/rpc
ipfs_gateway: http://35.160.120.126:8081
ipfs_host: 127.0.0.1
ipfs_port: 5001
ipfs_protocol: http
logging:
  files:
    error: logs/error.log
    main: logs/orchestrator.log
    performance: logs/performance.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  rotation:
    backup_count: 5
    max_size: 10MB
model_cache:
  cleanup_threshold: 0.9
  directory: ./model_cache
  max_size: 53687091200
  retention_days: 30
model_registry_address: '0xdB7d6AB1f17c6b31909aE466702703dAEf9269Cf'
monitoring:
  alerts:
    cpu_threshold: 90
    disk_threshold: 95
    error_rate_threshold: 0.1
    memory_threshold: 90
  health_check_interval: 30
  metrics_enabled: true
  metrics_interval: 60
network:
  auto_connect: true
  bootstrap_nodes:
  - https://bootstrap-node.onrender.com
  connection_timeout: 30
  discovery_interval: 30
  enable_discovery: true
  listen_port: 30303
  max_peers: 50
  request_timeout: 60
node_profile_registry_address: '0x3A220f351252089D385b29beca14e27F204c296A'
private_key: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
ray:
  host: 127.0.0.1
  num_cpus: null
  num_gpus: null
  port: 6379
ray_port: 6379
resources:
  cpu_contribution: 10
  gpu_contribution: 10
  max_cpu: 90
  max_ram: 80
  max_storage: 70
  max_vram: 90
  min_free_ram: 2147483648
  min_free_storage: 10737418240
  min_free_vram: 4294967296
  ram_contribution: 15
  storage_contribution: 5
  head_min_ram: 2147483648
  head_min_vram: 4294967296
security:
  api_key: null
  api_key_required: false
  cors_origins:
  - http://localhost:3000
  - http://localhost:8501
  - http://localhost:8080
  rate_limiting_enabled: true
vllm:
  gpu_memory_utilization: 0.8
  host: 127.0.0.1
  max_model_len: 2048
  max_tokens: 512
  port: 8000
  temperature: 0.7
  trust_remote_code: true
websocket:
  max_connections: 100
  port: 8546

# Additional configurations for main.py
model_name: "deepseek-r1-1.5b"
enable_mcp: true
mcp_max_iterations: 5
max_tokens: 512
temperature: 0.7
top_p: 0.9
