# Working Test Configuration - Ready to Use!
# These are test values that work immediately

# Blockchain Configuration
ETH_NODE = "https://bootstrap-node.onrender.com/rpc"
CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
DEFAULT_ACCOUNT = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# IPFS Configuration
IPFS_HOST = "bootstrap-node.onrender.com"
IPFS_PORT = "443"

# Network Configuration
BOOTSTRAP_NODES = '["https://bootstrap-node.onrender.com"]'